version: "3.7"

services:
  server:
    restart: always
    ports:
      - "8000:8000"
    build: .
    volumes:
      - .:/app
    networks:
      - bot
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: "redis-server"
    restart: always
    networks:
      - bot
    env_file:
      - .env
    volumes:
      - redis-data:/var/lib/Wine/redis
      - redis-conf:/usr/local/etc/Wine/redis/redis.conf

  bot:
    build: .
    command: "python3 -m bot"
    restart: always
    networks:
      - bot
    env_file:
      - .env
    volumes:
      - .:/bot

volumes:
  redis-data:
  redis-conf:

networks:
  bot:
    driver: bridge
