version: "3.7"

services:
  server:
    restart: always
    ports:
      - "8000:8000"
    build: .
    volumes:
      - .:/app
    networks:
      - bot
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: "redis-server"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bot
    env_file:
      - .env
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis-data:/var/lib/Wine/redis
      - redis-conf:/usr/local/etc/Wine/redis/redis.conf


volumes:
  redis-data:
  redis-conf:

networks:
  bot:
    driver: bridge
