# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Development Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    env:
      ENVY: ${{ secrets.ENVY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create env
        run: echo "$ENVY" > .env
      - name: "Build compose"
        run: docker compose up --build -d
